sonar.projectKey=advprog-2026-A17-project_bidmart-wallet-service-rust
sonar.organization=advprog-2026-a17-project
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=tests
sonar.exclusions=target/**
