name: Continuous Deployment

on:
  push:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Docker Build
        run: docker build -t bidmart-wallet-service-rust .

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
